### ISSUE TITLE
Seems to not work with `package:new` task

### ISSUE THREAD

**Issue by tunnckoCore** [generate/generate-dest#2]
Seems to not work with latest updates (of generate, generate-package, generate-readme and generate-dest) + cache clean and `generate-package`'s new task.

``` sh
% ❯ gen dest package:new                                                                                   July 17, 03:37:50
[03:37:53] starting generate
TypeError: Path must be a string. Received true
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1148:7)
    at Generate.Object.defineProperty.set [as cwd] (/home/charlike/.nvm/versions/node/v6.3.0/lib/node_modules/generate/node_modules/base-generators/node_modules/base-cwd/index.js:33:39)
    at Generate.<anonymous> (/home/charlike/.nvm/versions/node/v6.3.0/lib/node_modules/generate/lib/mixins.js:129:22)
    at Generate.Emitter.emit (/home/charlike/.nvm/versions/node/v6.3.0/lib/node_modules/generate/node_modules/component-emitter/index.js:133:20)
    at Generate.emit (/home/charlike/.nvm/versions/node/v6.3.0/lib/node_modules/generate/node_modules/base-task/index.js:47:19)
    at Generate.Emitter.mergeOptions (/home/charlike/.nvm/versions/node/v6.3.0/lib/node_modules/generate/node_modules/option-cache/index.js:114:16)
    at Generate.Emitter.option (/home/charlike/.nvm/versions/node/v6.3.0/lib/node_modules/generate/node_modules/option-cache/index.js:81:30)
    at Function.<anonymous> (/home/charlike/.nvm/versions/node/v6.3.0/lib/node_modules/generate/bin/generate.js:32:7)
    at Function.Emitter.emit (/home/charlike/.nvm/versions/node/v6.3.0/lib/node_modules/generate/node_modules/component-emitter/index.js:133:20)
```

**Comment by jonschlinkert** [comment]
Use `--dest` instead for now. I'll look into it thx.

**Comment by jonschlinkert** [comment]
@tunnckoCore did `gen dest` work for you before the past couple of days? I might know why it's broken if this just happened

**Comment by tunnckoCore** [comment]
In combination with `generate-package` don't know, but yea with other gens it worked and it works currently with most of them.

And btw, just ran for the first time `gen dest` only and it not created directory, is it normal?

Look that

![2016-07-17-15 13 22_1280x1024_scrot](https://cloud.githubusercontent.com/assets/5038030/16900595/14fb9392-4c31-11e6-9ac1-c9c63146180f.png)

_(cool workspace, huh? :laughing: i'm in the middle)_

**Comment by jonschlinkert** [comment]
> In combination with generate-package don't know, but yea with other gens it worked and it works currently with most of them.

Ok, would you mind trying something to see if we can get to the bottom of this? 

Try reversing the order of the non-dest generators:

``` sh
 $ gen dest package readme
```

Then 

``` sh
 $ gen dest readme package
```

Let's see if one of the two generators is not doing what it's supposed to. I suspect one of those will work, the other won't. If neither work, then I'm not sure. I'll have to did deeper

edit: indeed, looks like a great workspace!
